version: '3'
services:
  web1:
    image: johan1103/goorm:latest
    ports:
      - "80:8080"
    container_name: api-server
  nginx:
    container_name: nginx
    image: nginx:1.22.1-alpine
    ports:
      - "80:80"
    volumes:
      - /home/ubuntu/goorm/nginx/etc/letsencrypt:/etc/letsencrypt
      - /home/ubuntu/goorm/nginx/var/lib/letsencrypt:/var/lib/letsencrypt
      - /home/ubuntu/goorm/goormtone-environment/nginx/sites.conf:/etc/nginx/conf.d/sites.conf
      - /home/ubuntu/goorm/goormtone-environment/nginx/sites-enabled:/etc/nginx/sites-enabled